-- ────────────────────────────────────────────────────────────
-- Migration: teams + team_members (many-to-many roster filter)
-- Project:   eq-field-app (SKS-Live clone)
-- Version:   3.4.78
-- Created:   2026-05-20
-- Applied:   SKS  (nspbmirochztcjijmcrx) — pending
-- ────────────────────────────────────────────────────────────
-- Field request from Ben Ritchie: supervisors need to filter the
-- roster down to just their crew. Many people sit across multiple
-- crews (e.g. an apprentice rotating between Equinix and AirTrunk),
-- so a one-team-per-person column on people doesn't model reality.
--
-- This migration adds:
--   • teams           — named, coloured filter groups (per-org)
--   • team_members    — link table for the many-to-many
--
-- Teams are PURE FILTER METADATA. They do not affect availability,
-- scheduling rules, notifications, or payroll. They are a view
-- concept only — the roster grid filters down to the selected
-- team's members, and the contacts page does the same. If a more
-- semantic 'team' concept ever ships (e.g. team-based digest emails),
-- it can be layered on top of this same table without migration.
--
-- RLS pattern matches the existing leave_balances / checkins /
-- audit_log tables: anon SELECT(true), anon writes require org_id.
-- The real security boundary is the staff/supervisor access code
-- at the gate + the org_id auto-stamping in scripts/supabase.js.
--
-- Idempotent: every CREATE / ALTER / ADD is guarded with IF NOT
-- EXISTS so re-running is a no-op.
-- ────────────────────────────────────────────────────────────

-- ─── 1. teams ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.teams (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      uuid NOT NULL,
  name        text NOT NULL,
  color       text NOT NULL DEFAULT '#7C77B9',  -- SKS purple as the neutral default
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT teams_name_per_org_unique UNIQUE (org_id, name)
);

CREATE INDEX IF NOT EXISTS teams_org_idx ON public.teams (org_id);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='teams' AND policyname='anon_select_teams') THEN
    CREATE POLICY anon_select_teams ON public.teams
      FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='teams' AND policyname='anon_insert_teams') THEN
    CREATE POLICY anon_insert_teams ON public.teams
      FOR INSERT WITH CHECK (org_id IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='teams' AND policyname='anon_update_teams') THEN
    CREATE POLICY anon_update_teams ON public.teams
      FOR UPDATE USING (org_id IS NOT NULL) WITH CHECK (org_id IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='teams' AND policyname='anon_delete_teams') THEN
    CREATE POLICY anon_delete_teams ON public.teams
      FOR DELETE USING (org_id IS NOT NULL);
  END IF;
END $$;

-- ─── 2. team_members (link table) ────────────────────────────
CREATE TABLE IF NOT EXISTS public.team_members (
  team_id    bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  person_id  bigint NOT NULL,  -- FK to people.id added below if not exists
  org_id     uuid   NOT NULL,
  added_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (team_id, person_id)
);

-- Person FK is added separately so we can guard with IF NOT EXISTS
-- in case the people PK shape changes later. ON DELETE CASCADE so
-- hard-deleting a person reaps their team memberships; soft-delete
-- (archived flag) leaves memberships intact, and the UI filters
-- archived people out of team views by default.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'team_members_person_id_fkey'
      AND conrelid = 'public.team_members'::regclass
  ) THEN
    ALTER TABLE public.team_members
      ADD CONSTRAINT team_members_person_id_fkey
        FOREIGN KEY (person_id) REFERENCES public.people(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS team_members_person_idx ON public.team_members (person_id);
CREATE INDEX IF NOT EXISTS team_members_org_idx    ON public.team_members (org_id);

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='team_members' AND policyname='anon_select_team_members') THEN
    CREATE POLICY anon_select_team_members ON public.team_members
      FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='team_members' AND policyname='anon_insert_team_members') THEN
    CREATE POLICY anon_insert_team_members ON public.team_members
      FOR INSERT WITH CHECK (org_id IS NOT NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='team_members' AND policyname='anon_delete_team_members') THEN
    CREATE POLICY anon_delete_team_members ON public.team_members
      FOR DELETE USING (org_id IS NOT NULL);
  END IF;
  -- No UPDATE policy: team_members rows are immutable once written.
  -- To move a person between teams, the UI deletes + re-inserts.
END $$;

COMMENT ON TABLE public.teams IS
  'Named filter groups for the roster (v3.4.78). Pure view metadata — does not affect availability or scheduling.';
COMMENT ON TABLE public.team_members IS
  'Many-to-many link between teams and people. A person can sit in multiple teams.';
COMMENT ON COLUMN public.teams.color IS
  'Hex colour (#RRGGBB) used for the 4px left-border on roster rows when team filter is set to All. Defaults to SKS purple.';
